language: ruby
cache: bundler

addons:
  apt:
    packages:
      - ca-certificates

script: bundle exec rake test

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: Y92VeqNKgeRR0yU82FSjljI1VihQFDZuFlwakAr+E6Fin/jFi8iqrha2Eryru33UkDXLsBJpy+vGabHfFw7eFxQ9oVAqeTjYrrglFJfBQ6NYbM56BshR9ZXpIIaGqgRrlfVGHElFWaU68GEtaPomUt+2rL2UlXDHwMfl9GrSNFQ=

deploy:
  provider: pages
  github-token: $GH_TOKEN
  name: Jekyll [automated]
  email: no-reply@connectbot.org
  local-dir: _site
  skip-cleanup: true
  on:
    repo: connectbot/connectbot.github.io
    branch: develop
  target-branch: master
  keep-history: true
  fqdn: connectbot.org
